// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using trabalhoLPCTentativaNumero2.Models;

namespace trabalhoLPCTentativaNumero2.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20181101232026_timeSpanAtt")]
    partial class timeSpanAtt
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("trabalhoLPCTentativaNumero2.Models.Chamado", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("clienteid");

                    b.Property<DateTime>("data");

                    b.Property<string>("descricao");

                    b.Property<TimeSpan?>("horaFim");

                    b.Property<TimeSpan>("horaInicio");

                    b.Property<int?>("situacaoid");

                    b.Property<TimeSpan?>("tempoDuracao");

                    b.HasKey("id");

                    b.HasIndex("clienteid");

                    b.HasIndex("situacaoid");

                    b.ToTable("Chamados");
                });

            modelBuilder.Entity("trabalhoLPCTentativaNumero2.Models.Cliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("email");

                    b.Property<string>("nome");

                    b.Property<int>("telefone");

                    b.HasKey("id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("trabalhoLPCTentativaNumero2.Models.Situacao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("nome");

                    b.HasKey("id");

                    b.ToTable("Situacoes");
                });

            modelBuilder.Entity("trabalhoLPCTentativaNumero2.Models.Chamado", b =>
                {
                    b.HasOne("trabalhoLPCTentativaNumero2.Models.Cliente", "cliente")
                        .WithMany()
                        .HasForeignKey("clienteid");

                    b.HasOne("trabalhoLPCTentativaNumero2.Models.Situacao", "situacao")
                        .WithMany()
                        .HasForeignKey("situacaoid");
                });
#pragma warning restore 612, 618
        }
    }
}
