// <auto-generated />
using Associados.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Associados.Repositories.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20181207194342_Intiial Migrations")]
    partial class IntiialMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("Associados.Domain.AssociadoRoot.Associado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("cep");

                    b.Property<string>("cidade");

                    b.Property<string>("cpf");

                    b.Property<DateTime>("dataNascimento");

                    b.Property<string>("email");

                    b.Property<string>("endereco");

                    b.Property<string>("nome");

                    b.Property<string>("uf");

                    b.HasKey("Id");

                    b.ToTable("Associado");
                });

            modelBuilder.Entity("Associados.Domain.DependenteRoot.Dependente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("AssociadoId");

                    b.Property<DateTime>("dataNascimento");

                    b.Property<string>("grauParentesco");

                    b.Property<string>("nome");

                    b.HasKey("Id");

                    b.HasIndex("AssociadoId");

                    b.ToTable("Dependente");
                });

            modelBuilder.Entity("Associados.Domain.UsarioRoot.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("login");

                    b.Property<string>("senha");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Associados.Domain.DependenteRoot.Dependente", b =>
                {
                    b.HasOne("Associados.Domain.AssociadoRoot.Associado")
                        .WithMany("dependentes")
                        .HasForeignKey("AssociadoId");
                });
#pragma warning restore 612, 618
        }
    }
}
